security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SECR:       ROLE_USER
        ROLE_COMP:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
         main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/formation/, role: [ROLE_ADMIN, ROLE_SECR, ROLE_COMP]}
        - { path: ^/entreprise/, role: [ROLE_ADMIN, ROLE_SECR]}
        - { path: ^/stagiaire/, role: [ROLE_ADMIN, ROLE_SECR]}
        - { path: ^/formateur/, role: ROLE_ADMIN }
        - { path: ^/session/, role: [ROLE_ADMIN, ROLE_COMP]}
        - { path: ^/categorie/, role: [ROLE_ADMIN, ROLE_COMP]}
        - { path: ^/, role: IS_AUTHENTICATED_FULLY}
