<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
	public function findAllWithFormation()
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT s, f
				FROM AppBundle:Session s
				JOIN s.formation f'
			);

		return $query->getResult();
	}

	public function findAllWithFormateur()
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT s, f
				FROM AppBundle:Session s
				JOIN s.formateur f'
			);

		return $query->getResult();
	}
}
